version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /docs
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/mysqlqueue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/natsqueue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/postgresqueue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/rabbitmqqueue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/redisqueue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/sqlitequeue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/sqlqueuecore
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /driver/sqsqueue
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /examples
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /integration
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
