package busruntime

import (
	"context"
	"sync"
)

// DeliverySettlement defers facts that become true only after a worker commits broker settlement.
// Its zero value is ready for use, and Commit is idempotent.
type DeliverySettlement struct {
	mu                        sync.Mutex
	committed                 bool
	applicationStateCommitted bool
	callbacks                 []func()
}

// DeliverySettlementIdentity is an opaque, comparable identity for one
// physical handler invocation. It permits correlation without exposing the
// driver's authority to commit the underlying settlement.
type DeliverySettlementIdentity struct {
	settlement *DeliverySettlement
}

type deliverySettlementContextKey struct{}
type deliveryProvenanceContextKey struct{}

// DeliveryProvenance identifies the current settlement generation and any
// earlier generation whose durable delivery definitely remained unsettled.
// Workflow state must independently prove which generation owns a transition.
type DeliveryProvenance struct {
	// GenerationID is an opaque identifier generated by the settlement owner
	// for the physical delivery currently invoking the handler.
	GenerationID string
	// RecoveredGenerationID identifies the earlier unsettled generation when
	// that identity survived reclamation.
	RecoveredGenerationID string
	// Recovered reports stale-generation evidence even when a legacy delivery
	// did not retain an owner identifier.
	Recovered bool
}

// WithDeliverySettlement attaches one settlement boundary to a handler context.
// Drivers that acknowledge or delete deliveries after handler execution use the returned value to commit deferred facts.
func WithDeliverySettlement(ctx context.Context) (context.Context, *DeliverySettlement) {
	if ctx == nil {
		ctx = context.Background()
	}
	settlement := &DeliverySettlement{}
	return context.WithValue(ctx, deliverySettlementContextKey{}, settlement), settlement
}

// DeliverySettlementIdentityFromContext returns the opaque identity for the
// physical settlement boundary attached to ctx.
func DeliverySettlementIdentityFromContext(ctx context.Context) (DeliverySettlementIdentity, bool) {
	settlement, ok := deliverySettlementFromContext(ctx)
	if !ok {
		return DeliverySettlementIdentity{}, false
	}
	return DeliverySettlementIdentity{settlement: settlement}, true
}

// deliverySettlementFromContext returns the driver-owned mutable settlement
// boundary without exposing settlement authority outside this package.
func deliverySettlementFromContext(ctx context.Context) (*DeliverySettlement, bool) {
	if ctx == nil {
		return nil, false
	}
	settlement, ok := ctx.Value(deliverySettlementContextKey{}).(*DeliverySettlement)
	return settlement, ok && settlement != nil
}

// WithDeliveryProvenance attaches settlement-owner generation identity to one
// physical handler invocation. Callers must not manufacture recovery evidence
// for an ordinary duplicate.
func WithDeliveryProvenance(ctx context.Context, provenance DeliveryProvenance) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	return context.WithValue(ctx, deliveryProvenanceContextKey{}, provenance)
}

// DeliveryProvenanceFromContext returns settlement-owner generation identity
// without treating it as proof of a workflow transition.
func DeliveryProvenanceFromContext(ctx context.Context) (DeliveryProvenance, bool) {
	if ctx == nil {
		return DeliveryProvenance{}, false
	}
	provenance, ok := ctx.Value(deliveryProvenanceContextKey{}).(DeliveryProvenance)
	return provenance, ok
}

// MarkDeliveryApplicationStateCommitted records that the current generation
// durably mutated application state before physical delivery settlement. SQL
// drivers use this only to preserve truthful provenance across a later
// same-attempt infrastructure redelivery.
func MarkDeliveryApplicationStateCommitted(ctx context.Context) bool {
	settlement, ok := deliverySettlementFromContext(ctx)
	if !ok {
		return false
	}
	settlement.mu.Lock()
	settlement.applicationStateCommitted = true
	settlement.mu.Unlock()
	return true
}

// ApplicationStateCommitted reports whether the current generation durably
// mutated application state before the driver attempted physical settlement.
func (s *DeliverySettlement) ApplicationStateCommitted() bool {
	if s == nil {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.applicationStateCommitted
}

// DeferUntilDeliveryCommitted registers fn when ctx carries a driver-owned settlement boundary.
// It returns false when the driver cannot report settlement, allowing callers to preserve legacy immediate behavior.
func DeferUntilDeliveryCommitted(ctx context.Context, fn func()) bool {
	if fn == nil {
		return false
	}
	settlement, ok := deliverySettlementFromContext(ctx)
	if !ok {
		return false
	}
	settlement.deferCommit(fn)
	return true
}

// Commit publishes every deferred fact after the driver has positively settled the delivery.
func (s *DeliverySettlement) Commit() {
	if s == nil {
		return
	}
	s.mu.Lock()
	if s.committed {
		s.mu.Unlock()
		return
	}
	s.committed = true
	callbacks := s.callbacks
	s.callbacks = nil
	s.mu.Unlock()

	for _, callback := range callbacks {
		invokeDeliveryCommit(callback)
	}
}

// deferCommit queues a callback or invokes it immediately when settlement already committed.
func (s *DeliverySettlement) deferCommit(fn func()) {
	s.mu.Lock()
	if !s.committed {
		s.callbacks = append(s.callbacks, fn)
		s.mu.Unlock()
		return
	}
	s.mu.Unlock()
	invokeDeliveryCommit(fn)
}

// invokeDeliveryCommit isolates deferred telemetry so it cannot invalidate an already committed broker acknowledgement.
func invokeDeliveryCommit(fn func()) {
	defer func() {
		_ = recover()
	}()
	fn()
}
