#!/usr/bin/env bash
set -euo pipefail

out_file="${1:-docs/compatibility-matrix.md}"
mkdir -p "$(dirname "${out_file}")"

tmp_rows="$(mktemp)"
trap 'rm -f "${tmp_rows}"' EXIT

{
  echo "redis|redis:7|integration/all,integration/bus,integration/root"
  echo "mysql|mysql:8.0|integration/all,integration/bus,integration/root"
  echo "postgres|postgres:16|integration/all,integration/bus,integration/root"
  echo "sqlite|n/a (in-process sqlite driver)|integration/all,integration/bus,integration/root"
  echo "nats|nats:2|integration/all,integration/bus,integration/root"
  echo "sqs|localstack/localstack:3.8 (SQS emulator)|integration/all,integration/bus,integration/root"
  echo "rabbitmq|rabbitmq:3 / rabbitmq:3.12-management / rabbitmq:3.13-management|integration/all,integration/bus,integration/root"
  echo "null|n/a (in-process)|integration/all"
  echo "sync|n/a (in-process)|integration/all"
  echo "workerpool|n/a (in-process)|integration/all"
} >"${tmp_rows}"

generated_at="$(date -u +%Y-%m-%d)"

{
  cat <<EOF
<!-- generated by scripts/gen-compatibility-matrix.sh; edit the script or integration image pins -->
# Compatibility Matrix (CI-Tested)

This matrix summarizes backend/runtime versions exercised by CI integration suites in this repository. It is intended to be referenced from release notes.

Generated: ${generated_at} (UTC)

## CI sources

- \`.github/workflows/test.yml\` (\`integration-all\` matrix)
- \`.github/workflows/soak.yml\` (evidence / soak / chaos / flake-repeat)
- \`integration/all\`, \`integration/bus\`, \`integration/root\` (pinned testcontainer images)

## Backends

| Backend | CI-tested version/runtime | Coverage source |
|---|---|---|
EOF
  while IFS='|' read -r backend version source; do
    printf '| `%s` | `%s` | `%s` |\n' "${backend}" "${version}" "${source}"
  done <"${tmp_rows}"
  cat <<'EOF'

## Notes

- Container-backed backends are pinned by integration test image tags in repo code.
- `sqs` uses LocalStack as an emulator in CI, not AWS-managed SQS.
- RabbitMQ coverage spans multiple pinned images across suites; all listed tags are CI-exercised.
EOF
} >"${out_file}"

echo "Wrote ${out_file}"
