name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test ./... -v

      - name: Run unit tests with coverage
        run: go test -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  race:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: go mod tidy

      - name: Run race tests
        run: go test -race ./...

  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend: [redis, mysql, postgres, sqlite]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: go mod tidy

      - name: Run integration tests
        env:
          RUN_INTEGRATION: "1"
          INTEGRATION_BACKEND: ${{ matrix.backend }}
        run: go test -tags integration ./...
